#!/usr/bin/env python3
"""
Keep the dashboard's "How to use this site" guide, the mirrored README
section, and Curb Your Spending's "Start here" list in sync with real
feature changes, using the Claude API. Run daily by
.github/workflows/update-site-guide.yml.

Requires the ANTHROPIC_API_KEY secret. Without it, the workflow logs a
clear message and exits 0 rather than failing every day.

How it decides what to write:
  1. Reads .github/site-guide-sync-state.json for the SHA it last
     evaluated (last_synced_sha). First run just records HEAD and exits
     -- there is no prior baseline to diff against yet.
  2. Diffs index.html, README.md, and InputForm.jsx between that SHA and
     HEAD. index.html's embedded `<script type="application/json"
     id="data-*">` blocks (GBFS/311/etc. payloads that change on every
     automated pull) are stripped before diffing, so routine data
     refreshes never trigger a guide update on their own.
  3. If nothing relevant changed, state is left as-is (so tomorrow's
     diff just grows) and the script exits without an API call.
  4. Otherwise it sends the diffs plus the current text of each
     "owned" block (the three marker-delimited regions below) to
     Claude, with instructions to only reflect actual changes in the
     diff -- never invent a feature -- and to return strict JSON.
  5. The response is applied mechanically: HTML/JS are regenerated by
     this script from validated fields (a list of guide items, a list
     of "Start here" strings), never pasted in raw from the model, so
     a malformed response fails loudly instead of corrupting a file.
  6. State only advances (to HEAD) after a successful, validated run,
     so a crash or API failure leaves it retryable tomorrow.

The three owned regions -- do not hand-edit their *contents* without
also nudging state past the SHA that introduced your edit, or this
script will overwrite it on the next run:
  - index.html:            <!-- SITE-GUIDE-ITEMS:START --> ... <!-- SITE-GUIDE-ITEMS:END -->
  - README.md:              <!-- HOW-TO-USE-THIS-SITE:START --> ... <!-- HOW-TO-USE-THIS-SITE:END -->
  - InputForm.jsx:          {/* SITE-GUIDE:START */} ... /* SITE-GUIDE:END */

Model: defaults to the SITE_GUIDE_MODEL env var if set, else
"claude-sonnet-5". If the Anthropic API rejects that model id (API
model names occasionally carry a dated suffix), set the
SITE_GUIDE_MODEL repository variable to the exact id from
https://docs.anthropic.com/en/docs/about-claude/models -- this script
does not guess or fall back silently.
"""
import json
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INDEX_HTML_PATH = ROOT / "index.html"
README_PATH = ROOT / "README.md"
INPUT_FORM_PATH = ROOT / "scooter-challenge" / "src" / "components" / "InputForm.jsx"
STATE_PATH = ROOT / ".github" / "site-guide-sync-state.json"

GUIDE_START, GUIDE_END = "<!-- SITE-GUIDE-ITEMS:START", "<!-- SITE-GUIDE-ITEMS:END -->"
README_START, README_END = "<!-- HOW-TO-USE-THIS-SITE:START", "<!-- HOW-TO-USE-THIS-SITE:END -->"
JSX_START, JSX_END = "{/* SITE-GUIDE:START", "/* SITE-GUIDE:END */"

ANTHROPIC_MODEL = os.environ.get("SITE_GUIDE_MODEL", "claude-sonnet-5")
ANTHROPIC_API_URL = "https://api.anthropic.com/v1/messages"
MAX_README_CHARS = 6000

DATA_SCRIPT_RE = re.compile(
    r'(<script type="application/json" id="data-[^"]+">)(.*?)(</script>)', re.DOTALL
)


def run_git(*args):
    result = subprocess.run(["git", *args], cwd=ROOT, capture_output=True, text=True)
    if result.returncode != 0:
        return None
    return result.stdout


def file_at_sha(sha, relative_path):
    return run_git("show", f"{sha}:{relative_path}")


def strip_data_scripts(html):
    def _redact(match):
        omitted = len(match.group(2))
        return f"{match.group(1)}[[DATA OMITTED -- {omitted} bytes, not a feature change]]{match.group(3)}"

    return DATA_SCRIPT_RE.sub(_redact, html)


def strip_owned_region(text, start_marker, end_marker):
    """Blank out a marker-delimited region this script itself maintains, so a
    prior day's own edit never shows up as "new" in the next day's diff."""
    if text is None:
        return None
    inner = extract_between(text, start_marker, end_marker)
    if inner is None:
        return text
    # Fixed text, not dependent on the (differing) old/new content length --
    # otherwise this script's own prior edit would never fully collapse to
    # "no diff" and every run would re-trigger an API call on itself.
    placeholder = "[[OWNED REGION OMITTED -- maintained by this script, not a feature change]]"
    return replace_between(text, start_marker, end_marker, placeholder)


def unified_diff(old_text, new_text, label):
    import difflib

    if old_text is None:
        old_text = ""
    diff = difflib.unified_diff(
        old_text.splitlines(keepends=True),
        new_text.splitlines(keepends=True),
        fromfile=f"a/{label}",
        tofile=f"b/{label}",
    )
    return "".join(diff)


def extract_between(text, start_marker, end_marker):
    start = text.find(start_marker)
    end = text.find(end_marker)
    if start == -1 or end == -1 or end < start:
        return None
    inner_start = text.find("-->", start)
    if start_marker.startswith("<!--") and inner_start != -1 and inner_start < end:
        return text[inner_start + 3 : end]
    line_end = text.find("*/}", start)
    if start_marker.startswith("{/*") and line_end != -1 and line_end < end:
        return text[line_end + 3 : end]
    return text[start + len(start_marker) : end]


def replace_between(text, start_marker, end_marker, new_inner):
    start = text.find(start_marker)
    end = text.find(end_marker)
    if start == -1 or end == -1 or end < start:
        raise SystemExit(f"Markers {start_marker!r}/{end_marker!r} not found or out of order -- refusing to guess.")
    marker_close = text.find("-->", start) if start_marker.startswith("<!--") else text.find("*/}", start)
    marker_close_len = 3
    prefix_end = marker_close + marker_close_len
    return text[:prefix_end] + new_inner + text[end:]


def load_state():
    if not STATE_PATH.exists():
        return None
    return json.loads(STATE_PATH.read_text())


def save_state(sha):
    STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
    STATE_PATH.write_text(json.dumps({"last_synced_sha": sha}, indent=2) + "\n")


def format_guide_items_html(items):
    lines = []
    for item in items:
        number = item["number"]
        title = item["title"].replace("&", "&amp;")
        body = item["body"]
        lines.append(f'      <section class="guide-item"><h3>{number} · {title}</h3><p>{body}</p></section>')
    return "\n" + "\n".join(lines) + "\n      "


def format_start_here_block(items):
    lines = ["\n          {[\n"]
    for item in items:
        lines.append(f"            {json.dumps(item, ensure_ascii=False)},\n")
    lines.append("          ]\n          ")
    return "".join(lines)


def validate_guide_items(items):
    if not items or not isinstance(items, list):
        raise SystemExit("Model returned no guide items -- refusing to write an empty guide.")
    for i, item in enumerate(items, start=1):
        if not isinstance(item, dict) or not {"number", "title", "body"} <= item.keys():
            raise SystemExit(f"Guide item {i} missing required fields (number/title/body).")
        if item["number"] != i:
            raise SystemExit(f"Guide items are not sequentially numbered (item {i} has number={item['number']!r}).")
        if not item["title"].strip() or not item["body"].strip():
            raise SystemExit(f"Guide item {i} has an empty title or body.")


def validate_start_here(items):
    if not items or not isinstance(items, list) or not all(isinstance(x, str) and x.strip() for x in items):
        raise SystemExit("Model returned an invalid Start Here list (expected a non-empty list of non-empty strings).")
    if len(items) > 8:
        raise SystemExit(f"Start Here list implausibly long ({len(items)} items) -- refusing to apply.")


def validate_readme_section(text):
    if not text or not text.strip():
        raise SystemExit("Model returned an empty README section.")
    if len(text) > MAX_README_CHARS:
        raise SystemExit(f"README section implausibly long ({len(text)} chars > {MAX_README_CHARS}) -- refusing to apply.")
    if GUIDE_START in text or README_START in text or JSX_START in text:
        raise SystemExit("Model's README section contains a marker string -- refusing to apply (would corrupt future syncs).")


def call_claude(prompt):
    import requests

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("ANTHROPIC_API_KEY not set -- skipping (see workflow for setup instructions).")
        sys.exit(0)

    response = requests.post(
        ANTHROPIC_API_URL,
        headers={
            "x-api-key": api_key,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        },
        json={
            "model": ANTHROPIC_MODEL,
            "max_tokens": 4096,
            "messages": [{"role": "user", "content": prompt}],
        },
        timeout=120,
    )
    if response.status_code != 200:
        raise SystemExit(f"Anthropic API returned {response.status_code}: {response.text[:2000]}")

    payload = response.json()
    text = "".join(block.get("text", "") for block in payload.get("content", []) if block.get("type") == "text")
    text = text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\n", "", text)
        text = re.sub(r"\n```$", "", text)
    try:
        return json.loads(text)
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Model did not return valid JSON: {exc}\n---\n{text[:2000]}")


PROMPT_TEMPLATE = """\
You keep a public data dashboard's own user-facing documentation honest and in sync with its code. You do NOT write marketing copy or invent features -- every sentence you produce must be traceable to an actual change in the diffs below. If a diff shows nothing that changes user-facing behavior (e.g. only internal refactors, styling, or the site's own automation), say so and set "changed": false.

There are three independently-owned regions. You may update any subset of them (only what the diffs actually justify), or none.

## 1. Dashboard "How to use this site" guide (index.html)

Current items (numbered list, each has a short title and one explanatory sentence or two):
{guide_items_current}

Diff of index.html since the last sync (embedded data-* JSON payloads are redacted -- ignore any [[DATA OMITTED]] markers, they are routine data refreshes, not feature changes):
```diff
{index_diff}
```

## 2. README.md "How to Use This Site" section (mirrors the dashboard guide, shorter)

Current text:
```markdown
{readme_current}
```

Diff of README.md since the last sync:
```diff
{readme_diff}
```

## 3. Curb Your Spending "Start here" list (scooter-challenge/src/components/InputForm.jsx)

Current items:
{start_here_current}

Diff of InputForm.jsx since the last sync:
```diff
{input_form_diff}
```

## Output

Return ONLY a single JSON object, no markdown fences, no commentary, matching exactly:

{{
  "changed": boolean,
  "summary": "one-line summary for a git commit message, or a short explanation of why nothing changed",
  "guide_items": null or [{{"number": 1, "title": "...", "body": "..."}}, ...] (the FULL replacement list, renumbered sequentially from 1, only if the dashboard guide needs a change),
  "readme_section": null or "full replacement markdown text for the README section, only if it needs a change (do not include the marker comments themselves)",
  "start_here_items": null or ["...", "...", ...] (the FULL replacement list, only if it needs a change)
}}

Rules:
- Only touch a region if the diffs show a real, user-facing reason to. Leave the other two as null.
- Never remove an existing guide item unless the diff shows the feature it describes was actually removed.
- Keep the existing terse, factual tone (no hype words like "powerful", "seamless", "revolutionary").
- guide_items titles are short (2-5 words); body is 1-2 plain sentences.
- start_here_items stays at 3-6 short imperative steps.
"""


def main():
    head_sha = run_git("rev-parse", "HEAD")
    if head_sha is None:
        raise SystemExit("Could not resolve HEAD SHA.")
    head_sha = head_sha.strip()

    state = load_state()
    if state is None:
        print(f"No prior sync state -- bootstrapping at {head_sha[:12]}. Nothing to compare yet.")
        save_state(head_sha)
        return

    last_sha = state["last_synced_sha"]
    if last_sha == head_sha:
        print("Already synced through HEAD. Nothing to do.")
        return

    old_index = file_at_sha(last_sha, "index.html")
    old_readme = file_at_sha(last_sha, "README.md")
    old_input_form = file_at_sha(last_sha, "scooter-challenge/src/components/InputForm.jsx")

    new_index = INDEX_HTML_PATH.read_text()
    new_readme = README_PATH.read_text()
    new_input_form = INPUT_FORM_PATH.read_text()

    def prep_index(text):
        if text is None:
            return ""
        return strip_owned_region(strip_data_scripts(text), GUIDE_START, GUIDE_END)

    def prep_readme(text):
        return strip_owned_region(text, README_START, README_END) if text is not None else ""

    def prep_jsx(text):
        return strip_owned_region(text, JSX_START, JSX_END) if text is not None else ""

    index_diff = unified_diff(prep_index(old_index), prep_index(new_index), "index.html")
    readme_diff = unified_diff(prep_readme(old_readme), prep_readme(new_readme), "README.md")
    input_form_diff = unified_diff(prep_jsx(old_input_form), prep_jsx(new_input_form), "InputForm.jsx")

    if not (index_diff.strip() or readme_diff.strip() or input_form_diff.strip()):
        print(f"No relevant changes since {last_sha[:12]}. Leaving state as-is.")
        return

    guide_items_current = extract_between(new_index, GUIDE_START, GUIDE_END)
    readme_current = extract_between(new_readme, README_START, README_END)
    start_here_current = extract_between(new_input_form, JSX_START, JSX_END)
    if guide_items_current is None or readme_current is None or start_here_current is None:
        raise SystemExit("One or more SITE-GUIDE markers are missing -- refusing to guess where to write.")

    prompt = PROMPT_TEMPLATE.format(
        guide_items_current=guide_items_current.strip(),
        index_diff=index_diff.strip() or "(no change)",
        readme_current=readme_current.strip(),
        readme_diff=readme_diff.strip() or "(no change)",
        start_here_current=start_here_current.strip(),
        input_form_diff=input_form_diff.strip() or "(no change)",
    )

    result = call_claude(prompt)
    if not isinstance(result, dict) or "changed" not in result or "summary" not in result:
        raise SystemExit(f"Model response missing required fields: {result!r}")

    print(f"Model summary: {result['summary']}")
    if not result["changed"]:
        save_state(head_sha)
        return

    touched = []

    if result.get("guide_items"):
        validate_guide_items(result["guide_items"])
        new_html = replace_between(new_index, GUIDE_START, GUIDE_END, format_guide_items_html(result["guide_items"]))
        INDEX_HTML_PATH.write_text(new_html)
        touched.append("index.html")

    if result.get("readme_section"):
        validate_readme_section(result["readme_section"])
        padded = "\n" + result["readme_section"].strip() + "\n"
        new_readme_text = replace_between(new_readme, README_START, README_END, padded)
        README_PATH.write_text(new_readme_text)
        touched.append("README.md")

    if result.get("start_here_items"):
        validate_start_here(result["start_here_items"])
        new_jsx = replace_between(new_input_form, JSX_START, JSX_END, format_start_here_block(result["start_here_items"]))
        INPUT_FORM_PATH.write_text(new_jsx)
        touched.append("InputForm.jsx")

    if not touched:
        print("Model said changed=true but provided no non-null fields -- treating as no-op.")

    (ROOT / ".github" / "site-guide-sync-summary.txt").write_text(result["summary"] + "\n")
    save_state(head_sha)
    print(f"Updated: {', '.join(touched) if touched else '(nothing)'}")


if __name__ == "__main__":
    main()
